### ISSUE TITLE
Identifying left and right pairs of modifier keys

### ISSUE THREAD

**Issue by Const4ntFlux** [dbkynd/controlcast#11]
Is it possible to make Controlcasts hotkey function identify which side of a modifier key pair is being used?
For example to distinguish between Left/right shift or left/right ctrl

I'm wondering about this because I ran into trouble trying to switch scenes with hotkeys in OBS while a game that uses ctrl and shift for gameplay and I would be switching actions in game while switching scenes in OBS even blocking certain actions in game after I triggered them via a hotkey command that uses one of the keys used in game.

Being able to use key commands that factor in left and right pair separation would be a nice feature to have for people casting and gaming with a one computer setup.

Of course OBS would have to support left/right detection for hotkeys as well.
I will check in with the OBS devs to see if it will be supported.

**Comment by octalmage** [comment]
It looks like this would be pretty easy to implement in RobotJS, each OS has a separate keycode for the right shift/control. I'll work on getting this done this week.
