### ISSUE TITLE
Pipe Controlcasts key commands

### ISSUE THREAD

**Issue by Const4ntFlux** [dbkynd/controlcast#15]
I'm running into an issue where I run out of free keys to assign to OBS.
Modifier keys get picked up by whatever application is in focus so they can't help with enlarging the pool of available keys.
For example: CTRL+1 as keyboard command to switch to a specific scene in OBS triggers an action in many games (in my case Fallout 4) when I assign this keystroke to a button in Controlcast.

Reassigning modifier keys in the games is often impossible or impractical. Since we can't distinguish between left and right modifier keys within OBS or Controlcast either and the numkeypad isn't recognized in Controlcast, this limits available keys for Controlcast drastically.
Which brings me to my question:
Can Controlcasts commands (keystrokes) be 'piped' through directly to OBS exclusively so no other application would be getting those commands to avoid overlap and triggering of actions in in-focus applications?
It is either that, a second PC for streaming where OBS is always in focus, or being able to set-up MIDI notes as keycommands for OBS, which Controlcast as well as OBS would have to implement.
Any ideas?

**Comment by dbkynd** [comment]
Will not be able to pipe key commands to OBS. But Controlcast now supports left/right modifiers and numpad buttons. There should be more than enough key combinations to use all the midi buttons on the controller.
