### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by Zelakto** [dbkynd/controlcast#21]
While installing the latest version, I keep experiencing this issue where it just loads a white screen. The loading GIF shows up, but when the program launches itself it just looks like this. ![https://i.zelakto.tv/m9FDqSy.png](https://i.zelakto.tv/m9FDqSy.png)

I've deleted the files in `C:\Users\user\AppData\Local\ControlCast` and have tried reinstalling, but I still don't have any luck.

**Comment by dbkynd** [comment]
I'm not quite sure what has caused this error, but I recently pushed 0.3.3 with a lot of internal tweaks. Please try installing 0.3.3 and see if that works. It may reset your key settings, but in 0.3.3 the config is stored in a more persistent location so it shouldn't happen again after.

**Comment by Zackery** [comment]
I just installed 0.3.4, doing so made ControlCast not open at all, however it is opened in my task manager. I deleted both settings locations and reinstalled again, I got the same issue.

**Comment by Zackery** [comment]
I've done some more testing and I've found the issue. It seems like the program will only launch if my launchpad isn't plugged into my computer for some odd reason. Once I start it without it plugged in, then plug in the launchpad and reload, it works correctly. If I restart the program with my launchpad in it launches normally as well.

**Comment by dbkynd** [comment]
Hmm, very odd. What model Launchpad are you using? It was originally designed for the Launchpad Mini, but now supports most of them.
Can you open your Device Manager and see what the launchpad device is called?
![image](https://cloud.githubusercontent.com/assets/10998787/24592567/f67711e6-17d5-11e7-874d-5e22ebf0df6d.png)

**Comment by Zackery** [comment]
I am also using the Launchpad Mini.
![Launchpad](https://i.zelakto.tv/iIn0EoJ.png)

**Comment by Zackery** [comment]
Also, I've just restarted my computer. The program seems to be launching normally now without me having to disconnect/reconnect my Launchpad.

**Comment by dbkynd** [comment]
Glad it's working for you now. 👍
