### ISSUE TITLE
More LED colors?

### ISSUE THREAD

**Issue by AquatikJustice** [dbkynd/controlcast#25]
Is there any way to implement more colors for the LEDs? The ability to add a myriad of colors would help greatly with organization and quickly figuring out which key you want to hit.

**Comment by dbkynd** [comment]
There is only one more color available on the Launchpad mini, Yellow. But it is so close to amber and low amber I thought it best to leave it out and just have a low and high setting for each one.

I think some of the other pads have blue and such, but afaik these colors below are available on all pads and would be the lowest common denominator.

#OFF: 12
#LOW_RED: 13
#RED: 15
#LOW_AMBER: 29
#AMBER: 63
#LOW_GREEN: 28
#GREEN: 60
#YELLOW: 62
