### ISSUE TITLE
Installation ??????

### ISSUE THREAD

**Issue by JoffrayBillon** [dbkynd/controlcast#27]
This question is realy dumb but I don't find any mention about how to install this (has an application or an OBS plugins,...).

Since Launchpad MK2 is realy close to the MK1 on MIDI input du you think it would work on OBS ?

Thanks

**Comment by dbkynd** [comment]
Control Cast is a stand alone application that you setup keyboard hotkeys on that control OBS scenes and such. If you go to the releases there is a 32 and 64 bit installer. https://github.com/dbkynd/controlcast/releases 
The MK2 should word, yes.

**Comment by JoffrayBillon** [comment]
Thanks there is no any link to the release page Google and the link you purpose on many forum are redirecting to https://github.com/dbkynd/controlcast which isn't linked to release page :) setup a link on this page could be great.

Thanks for help :).

**Comment by dbkynd** [comment]
People familiar with github typically know to look at the releases page for installation files.
I have not actively been trying to 'spread the word' as it were about this project, so it's good to hear people are recommending it to others on forums. 😄 
I'll consider adding an Installation section to the readme. Thanks!

**Comment by JoffrayBillon** [comment]
Yes it's good because people who are streaming are not all know git ;)
