### ISSUE TITLE
How to complile and run the code?

### ISSUE THREAD

**Issue by Djdcann** [dbkynd/controlcast#37]
Hi,

looking to make some modifications to this app, but I'm not sure where to start. It looks like it was done with Node.js which i'm unfamiliar with. If there's enough files in this repo to compile and run, would you mind putting some instructions in the README on how to do so? 

Hoping you see this @dbkynd 
I'll probably just be taking a really bad crack at it myself if no response

**Comment by dbkynd** [comment]
Yes, with Node.js installed (and therefore NPM) open a console in the root directory of the application folder and run ``npm start``
This will run the app locally. Grunt is used for building for release.

**Comment by Djdcann** [comment]
thank you!!!

**Comment by Djdcann** [comment]
Wasn't able to get the app running do to the modules being outdated?? npm install told me I needed .NET 2.0 SDK
