### ISSUE TITLE
This project is OUTDATED ~ check this issue i got the solution to all of your issues!

### ISSUE THREAD

**Issue by ruohki** [dbkynd/controlcast#56]
Hey since this is outdated I made a new project over at:

https://github.com/ruohki/lunchpad

its a whole new Application and supports almost (no pro MK3) Launchpads that are out there. It has a lot more features to offer.

you can also join the projects discord
https://discord.gg/4Ys9TRR

**Comment by dbkynd** [comment]
Indeed, this project is no longer maintained. But this is a pretty shitty way to go about trying to get people to use your software.

**Comment by ruohki123** [comment]
speaking of shitty way of doing things ~ blocking me completly giving no way of defending me ~ i tried to contact you but the only way seems to be twitter where you dont even bother to answer ... like in all your issues where people ask for help and hints. I just tried giving people an alternative. You dont even bother to flag that repo unmaintained now thats what i call a sh*t move
at least tell people you dont care about that project
