### ISSUE TITLE
Kill Audio doesn't work

### ISSUE THREAD

**Issue by Const4ntFlux** [dbkynd/controlcast#6]
The Kill Audio button in the lower left hand of the screen doesn't seem to work.

Expected behavior was: Any audio file being played back would stop when pressing Kill Audio.

**Comment by dbkynd** [comment]
This also works for me locally. Any error in the Chrome Dev Tools console?

Audio is played via the HTML5 audio API which was available to me by default by using Electron. http://electron.atom.io/

**Comment by dbkynd** [comment]
I expect once we fix #5 this will follow suit.

**Comment by Const4ntFlux** [comment]
Indeed it did.
