### ISSUE TITLE
Settings file being deleted upon update

### ISSUE THREAD

**Issue by Const4ntFlux** [dbkynd/controlcast#7]
Could we get a warning in the readme or a warning upon running the update to manually backup the config.json to avoid losing it (no pun intended) when updating the application?

**Comment by dbkynd** [comment]
The way Squirrel.Windows works with updates, there should never be an issue with overriding or corrupting the config.json file. Currently however, if you re-run any of the setup.exe files, it deletes the entire %localappdata%/ControlCast folder and remakes it. So I need to add a way to preserve any existing config for that scenario.

I'll add mention that the config can be overwritten by re-running Setup.exe in the README

**Comment by Const4ntFlux** [comment]
Great!
How could one update Controlcast without rerunning the setup.exe though?

**Comment by dbkynd** [comment]
ControlCast queries an Amazon S3 server periodically to check for updates automatically. When an update is detected, it automatically downloads in the background, prepares the new app alongside the old one inside the ``%localappdata/ControlCast%`` folder. Once ready, whenever you close and reopen the app, it automatically is on the latest version. I also display an update icon in the upper right of the window, which when pressed, closes and reopens to the latest version.

This is all done via Squirrel.Windows. It's pretty slick. It's the same as Discord and Slack if you use those apps.

**Comment by dbkynd** [comment]
Added warning in the README
